spring.application.name=placement
spring.datasource.url=jdbc:postgresql://localhost:5432/placement_db
spring.datasource.username=postgres
spring.datasource.password=Hari@1849

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration